package org.strategoxt.imp.debuggers.stratego.instrumentation.actions;

import java.io.File;

/**
 * Paths that are used by the compiler.
 * The instrumented Stratego files will be placed in the StrategoDirectory.
 * Java code generated by STRJ will be placed in the JavaDirectory.
 * The compiled java files will be in the BinDirectory. 
 * 
 * @author rlindeman
 *
 */
public interface ICompilerPaths {

	// create dir: .working/$module-name/$mode
	// in each $mode we have the following directories:
	// .working/$module-name/$mode/stratego
	// .working/$module-name/$mode/java
	// .working/$module-name/$mode/bin

	/**
	 * .working/$module-name/$mode/stratego
	 */
	public File getStrategoDirectory();
	
	/**
	 * .working/$module-name/$mode/java
	 * @return
	 */
	public File getJavaDirectory();
	/**
	 * .working/$module-name/$mode/bin
	 * @return
	 */
	public File getBinDirectory();
	
	/**
	 * .working/$module-name/$mode/logs
	 * @return
	 */
	public File getLogsDirectory();
}
